# === Этап сборки приложения ===
FROM maven:3.8.5-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# === Этап рантайма ===
FROM openjdk:11-jre-slim
WORKDIR /app

# Копируем собранный JAR из предыдущего этапа
COPY --from=build /app/target/RegAuth-*.jar app.jar

# Публикуем порт, на котором приложение слушает HTTP
EXPOSE 8080

# Команда запуска при старте контейнера
ENTRYPOINT ["java", "-jar", "app.jar"]
