# === Stage 1: Сборка приложения ===
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app

# Кэшируем зависимости
COPY pom.xml .
RUN mvn dependency:go-offline

# Копируем исходники и собираем
COPY src ./src
RUN mvn clean package -DskipTests

# === Stage 2: Рантайм образ ===
FROM openjdk:17-jdk-slim
WORKDIR /app

# Копируем собранный jar-файл
COPY --from=build /app/target/RegAuth-*.jar app.jar

# Порт, который слушает Spring Boot
EXPOSE 8080

# Старт приложения
ENTRYPOINT ["java", "-jar", "app.jar"]
