spring:
  profiles: dev

  datasource:             # ── PostgreSQL
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/RegAuth_db
    username: postgres
    password: 1234

  jpa:                    # ── Hibernate / JPA
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: security
    hibernate:
      ddl-auto: update       # локально генерируем/обновляем схему

jwt:
  secret: dev-secret-key     # можно держать в plain-text для локалки
