spring:
  # подключаем внешний файл со свойствами
  config:
    import: "optional:file:.env.properties"

  profiles:
    default: dev            # какой профиль брать, если не указан

  application:
    name: RegAuth

  # ── Liquibase ───────────────────────────────────────────────
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: security     # рабочие таблицы приложения
    liquibase-schema: public     # собственные таблицы Liquibase
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

  # ── сообщения i18n ─────────────────────────────────────────
  messages:
    basename: messages
    encoding: UTF-8

# ── логирование чтения конфигурации (можно выключить) ────────
logging:
  level:
    ru.krivi4.regauth: DEBUG
