--liquibase formatted sql

--changeset krivi4:001_create_people
CREATE TABLE people(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username varchar(100) NOT NULL UNIQUE,
                       password varchar(100) NOT NULL,
                       email varchar(100) NOT NULL,
                       phone_number varchar(20) NOT NULL UNIQUE,
                       enabled boolean NOT NULL DEFAULT(false),
                       created_at timestamp  DEFAULT now(),
                       last_login timestamp

);

--changeset krivi4:002_revoked_access_tokens
CREATE TABLE revoked_access_tokens (
                                jti UUID PRIMARY KEY,
                                expires_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_revoked_access_tokens_expires
    ON revoked_access_tokens (expires_at);


--changeset krivi4:003_otp_codes
CREATE TABLE otp_codes(
                          id UUID PRIMARY KEY,
                          phone_number varchar(20) NOT NULL,
                          code_hash varchar(100) NOT NULL,
                          expires_at timestamptz NOT NULL,
                          attempts int DEFAULT 0
);

CREATE INDEX idx_otp_expires on otp_codes (expires_at);

--changeset krivi4:004_refresh_tokens
CREATE TABLE refresh_tokens(
                               jti UUID PRIMARY KEY,
                               username VARCHAR(100) NOT NULL REFERENCES people(username) ON DELETE CASCADE,
                               expires_at TIMESTAMP NOT NULL,
                               revoked     BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_refresh_expires ON refresh_tokens(expires_at);
